doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        driver: 'pdo_pgsql'
        server_version: '12.1'
        charset: utf8
        default_table_options:
            charset: utf8
            collate:

        types:
            #User
            user_user_id: 'App\Infrastructure\IdentityAccess\Identity\Persistence\DoctrineType\UserIdType'
            user_user_email: 'App\Infrastructure\IdentityAccess\Identity\Persistence\DoctrineType\EmailType'


    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Identity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/domain/identity'
                prefix: 'App\Domain\IdentityAccess\Identity'
                alias: Identity
